sudo: required

language: generic

services:
 - docker

env:
 global:
  - REPO=https://github.com/ElementsProject/lightning.git
  - COMMIT=a4204226b46a31b3eb637967fb5c18d87d1cd9bb
  - TOOLCHAIN=aarch64-linux-android-clang
  - TARGETHOST=aarch64-linux-android
  - BITS=64

script:
  - docker run -v $PWD:/repo debian:buster@sha256:2f04d3d33b6027bb74ecc81397abe780649ec89f1a2af18d7022737d0482cefe /bin/bash -c "sh /repo/build_deps.sh && sh /repo/fetchbuild.sh $REPO $COMMIT $TOOLCHAIN $TARGETHOST $BITS /repo"
